using System.Text;

namespace NativeMethodsGenerator;

/// <summary>
/// Generates C# P/Invoke declarations from parsed C function signatures,
/// following the conventions used in NativeMethods.cs.
/// </summary>
public static class PInvokeGenerator
{
    private const string CallConvAttr =
        "[UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]";

    /// <summary>
    /// Generates the full NativeMethods.cs file content.
    /// </summary>
    public static string Generate(List<CFunction> functions, string version, string url)
    {
        var sb = new StringBuilder();
        sb.AppendLine( "// <auto-generated>");
        sb.AppendLine($"// This file was generated by NativeMethodsGenerator from RocksDB v{version} c.h header.");
        sb.AppendLine($"// {url}");
        sb.AppendLine( "// Do not edit manually — re-run the generator to update.");
        sb.AppendLine( "//");
        sb.AppendLine( "// Copyright (c) 2011-present, Facebook, Inc. All rights reserved.");
        sb.AppendLine( "// This source code is licensed under both the GPLv2 (found in the");
        sb.AppendLine( "// COPYING file in the root directory) and Apache 2.0 License");
        sb.AppendLine( "// (found in the LICENSE.Apache file in the root directory).");
        sb.AppendLine( "// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine( "using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine( "using System.Runtime.CompilerServices;");
        sb.AppendLine( "using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine( "namespace RocksDbNet.Native;");
        sb.AppendLine();
        sb.AppendLine( "[ExcludeFromCodeCoverage]");
        sb.AppendLine( "internal static unsafe partial class NativeMethods");
        sb.AppendLine( "{");
        sb.AppendLine( "    // ─────────────────────────────────────────────────────────────────────────");
        sb.AppendLine( "    // Version");
        sb.AppendLine( "    // ─────────────────────────────────────────────────────────────────────────");
        sb.AppendLine($"    internal const string RocksDbVersion = \"{version}\";");
        sb.AppendLine();

        // Group functions by prefix category
        var groups = GroupFunctions(functions);

        foreach (var (section, fns) in groups)
        {
            sb.AppendLine($"    // ─────────────────────────────────────────────────────────────────────────");
            sb.AppendLine($"    // {section}");
            sb.AppendLine($"    // ─────────────────────────────────────────────────────────────────────────");
            sb.AppendLine();

            foreach (var fn in fns)
            {
                GenerateFunction(sb, fn);
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateFunction(StringBuilder sb, CFunction fn)
    {
        var returnType = MapCTypeToManaged(fn.ReturnType, isReturn: true, fn.Name);
        var parameters = new List<string>();
        var hasStringParam = false;

        var usedNames = new Dictionary<string, int>();

        for (int i = 0; i < fn.Parameters.Count; i++)
        {
            var p = fn.Parameters[i];
            if (p.Type == "..." || p.Type == "void")
                continue; // Skip varargs and bare void params

            var isLastParam = i == fn.Parameters.Count - 1;
            var isErrptr = IsErrorPointer(p, isLastParam);

            if (isErrptr)
            {
                parameters.Add("ref nint errptr");
                continue;
            }

            var managedType = MapCTypeToManaged(p.Type, isReturn: false, fn.Name, p.Name);
            var paramName = SanitizeParamName(p.Name);

            // Generate a meaningful name for unnamed parameters
            if (string.IsNullOrEmpty(paramName) || paramName == "arg")
            {
                paramName = GenerateParamName(p.Type, i);
            }

            // Disambiguate duplicate names within the same function
            paramName = DeduplicateName(paramName, usedNames);

            // Check if this is a const char* input string parameter
            if (IsStringInputParam(p.Type, p.Name, fn.Name))
            {
                hasStringParam = true;
                parameters.Add($"string {paramName}");
            }
            // Check if this is a size_t output parameter (paired with a returned pointer)
            else if (IsOutSizeParam(p, fn, i))
            {
                parameters.Add($"out nuint {paramName}");
            }
            else
            {
                parameters.Add($"{managedType} {paramName}");
            }
        }

        // Emit LibraryImport attribute
        var libImport = hasStringParam
            ? $"[LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]"
            : $"[LibraryImport(LibName)]";
        sb.AppendLine($"    {libImport}");
        sb.AppendLine($"    {CallConvAttr}");

        if (parameters.Count == 0)
        {
            sb.AppendLine($"    internal static partial {returnType} {fn.Name}();");
        }
        else if (parameters.Count <= 2)
        {
            var paramStr = string.Join(", ", parameters);
            sb.AppendLine($"    internal static partial {returnType} {fn.Name}({paramStr});");
        }
        else
        {
            sb.AppendLine($"    internal static partial {returnType} {fn.Name}(");
            for (int i = 0; i < parameters.Count; i++)
            {
                var suffix = i < parameters.Count - 1 ? "," : ");";
                sb.AppendLine($"        {parameters[i]}{suffix}");
            }
        }
    }

    /// <summary>
    /// Maps a C type string to the corresponding C# managed type for P/Invoke.
    /// </summary>
    private static string MapCTypeToManaged(string cType, bool isReturn, string funcName, string paramName = "")
    {
        // Normalize
        var t = cType.Trim();

        // void
        if (t == "void")
            return "void";

        // Function pointer types → nint
        if (t.Contains("(*)") || t.Contains("(*"))
            return "nint";

        // Exact well-known types
        return t switch
        {
            // Unsigned char / bool
            "unsigned char" => "byte",
            "unsigned char*" => "byte*",
            "const unsigned char*" => "byte*",
            "unsigned char**" => "byte**",

            // char pointers
            "char*" => isReturn ? "nint" : "byte*",
            "const char*" => isReturn ? "byte*" : "byte*",
            "char**" => "byte**",
            "const char**" => "byte**",
            "const char* const*" => "byte**",

            // void pointers
            "void*" => "nint",
            "const void*" => "nint",
            "void**" => "nint*",

            // size_t
            "size_t" => "nuint",
            "size_t*" => "nuint*",
            "const size_t*" => "nuint*",

            // Fixed-width integers
            "uint64_t" => "ulong",
            "int64_t" => "long",
            "uint32_t" => "uint",
            "int32_t" => "int",
            "uint16_t" => "ushort",
            "int16_t" => "short",
            "uint8_t" => "byte",
            "int8_t" => "sbyte",

            // Primitives
            "int" => "int",
            "unsigned int" => "uint",
            "unsigned" => "uint",
            "long" => "long",
            "unsigned long" => "ulong",
            "double" => "double",
            "float" => "float",
            "char" => "sbyte",

            // All rocksdb_*_t* types → nint (opaque handle)
            _ when IsRocksDbOpaquePointer(t) => "nint",

            // rocksdb_*_t** → nint* (array of handles)
            _ when IsRocksDbOpaquePointerPointer(t) => "nint*",

            // Fallback for any other pointer type
            _ when t.EndsWith('*') => "nint",

            // Unknown type - use nint as safe fallback
            _ => "nint",
        };
    }

    private static bool IsRocksDbOpaquePointer(string t)
    {
        t = t.Replace("const ", "").Trim();
        return t.StartsWith("rocksdb_") && t.EndsWith("_t*") && !t.EndsWith("_t**");
    }

    private static bool IsRocksDbOpaquePointerPointer(string t)
    {
        t = t.Replace("const ", "").Trim();
        return t.StartsWith("rocksdb_") && t.EndsWith("_t**");
    }

    /// <summary>
    /// Determines if a parameter is the char** errptr error output parameter.
    /// Convention: last parameter named "errptr" of type char**.
    /// </summary>
    private static bool IsErrorPointer(CParam p, bool isLast)
    {
        return isLast &&
               p.Name == "errptr" &&
               (p.Type.Contains("char**") || p.Type.Contains("char **"));
    }

    /// <summary>
    /// Determines if a const char* parameter should be marshaled as a managed string.
    /// Heuristic: input const char* with names like "name", "path", "dir", "propname",
    /// "column_family_name", etc. — not buffer/key parameters.
    /// </summary>
    private static bool IsStringInputParam(string cType, string paramName, string funcName)
    {
        if (!cType.StartsWith("const char*") && cType != "const char *")
            return false;

        // Don't treat as string if it's a function pointer
        if (cType.Contains("(*"))
            return false;

        // Don't treat as string if it's a pointer-to-pointer
        if (cType.Contains("**"))
            return false;

        // Names that indicate a managed string (file path, db name, property name, etc.)
        var stringParamNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "name", "path", "dir", "db_dir", "wal_dir", "checkpoint_dir",
            "propname", "column_family_name", "secondary_path",
            "db_path", "backup_dir", "dbname",
        };

        if (stringParamNames.Contains(paramName))
            return true;

        // For general const char* that's a single pointer with a name suggesting a string
        if (paramName.EndsWith("_path") || paramName.EndsWith("_dir") ||
            paramName.EndsWith("_name") || paramName.EndsWith("name"))
            return true;

        return false;
    }

    /// <summary>
    /// Checks if a size_t* param is an output size for a returned pointer.
    /// E.g., rocksdb_get returns char* and has a size_t* vallen output parameter.
    /// </summary>
    private static bool IsOutSizeParam(CParam p, CFunction fn, int index)
    {
        if (p.Type != "size_t*")
            return false;

        // If the function returns a pointer type and this is the last non-error param,
        // or the param name ends with "len" / "length" / "size", treat as output.
        var name = p.Name.ToLowerInvariant();
        if (name.EndsWith("len") || name.EndsWith("length") || name == "size" || name.EndsWith("_len"))
        {
            // Check if there's only one such param and it seems like an output
            // Only mark as 'out' if return type is a pointer (returning a buffer with length)
            var retType = fn.ReturnType.Trim();
            if (retType.EndsWith('*'))
                return true;

            // Also for functions like _get_db_identity where the size is output
            if (fn.Parameters.Count(pp => pp.Type == "size_t*") == 1)
                return true;
        }

        return false;
    }

    private static string SanitizeParamName(string name)
    {
        if (string.IsNullOrEmpty(name))
            return "";

        // C# reserved keywords
        return name switch
        {
            "lock" => "@lock",
            "object" => "@object",
            "string" => "@string",
            "params" => "@params",
            "event" => "@event",
            "override" => "@override",
            "base" => "@base",
            _ => name,
        };
    }

    /// <summary>
    /// Generates a meaningful parameter name based on the C type when the header omits one.
    /// </summary>
    private static string GenerateParamName(string cType, int index)
    {
        var t = cType.Replace("const ", "").Replace("*", "").Trim();
        return t switch
        {
            "rocksdb_t" => "db",
            _ when t.StartsWith("rocksdb_") && t.EndsWith("_t") =>
                t["rocksdb_".Length..^"_t".Length],
            "size_t" => "len",
            "int" => "val",
            "unsigned int" => "val",
            "unsigned char" => "val",
            "char" => "str",
            "uint64_t" => "val",
            "int64_t" => "val",
            "uint32_t" => "val",
            "int32_t" => "val",
            "double" => "val",
            "float" => "val",
            "void" => "ptr",
            _ => $"arg{index}",
        };
    }

    /// <summary>
    /// Ensures parameter names are unique within a function by appending a numeric suffix.
    /// </summary>
    private static string DeduplicateName(string name, Dictionary<string, int> usedNames)
    {
        if (!usedNames.TryGetValue(name, out int count))
        {
            usedNames[name] = 1;
            return name;
        }

        usedNames[name] = count + 1;
        var newName = $"{name}{count + 1}";
        usedNames[newName] = 1;
        return newName;
    }

    /// <summary>
    /// Groups functions into logical sections based on their name prefix.
    /// </summary>
    private static List<(string Section, List<CFunction> Functions)> GroupFunctions(List<CFunction> functions)
    {
        var sectionOrder = new List<string>
        {
            "DB open / close",
            "DB identity / sequence number",
            "Column families",
            "Write / Put / Delete / Merge",
            "Read / Get",
            "Pinnable slice",
            "Snapshot",
            "Iterator",
            "Properties",
            "Flush / Compact / WAL",
            "Write batch",
            "Write batch (write-index)",
            "Options",
            "Read options",
            "Write options",
            "Flush options",
            "Compact options",
            "Block-based table options",
            "Cuckoo table options",
            "Plain table options",
            "Cache",
            "Filter policy",
            "Slice transform",
            "Merge operator",
            "Rate limiter",
            "Env",
            "Env options",
            "SST file writer",
            "Ingest external file",
            "Compaction filter",
            "Compaction filter factory",
            "Comparator",
            "Checkpoint",
            "Backup engine",
            "Logger",
            "Event listener",
            "Transaction DB",
            "Optimistic transaction DB",
            "Transaction",
            "WriteBatchWi",
            "Status / Utilities",
        };

        var grouped = new Dictionary<string, List<CFunction>>();
        foreach (var section in sectionOrder)
            grouped[section] = [];

        grouped["Miscellaneous"] = [];

        foreach (var fn in functions)
        {
            var section = ClassifyFunction(fn.Name);
            if (!grouped.ContainsKey(section))
                grouped[section] = [];
            grouped[section].Add(fn);
        }

        var result = new List<(string, List<CFunction>)>();
        foreach (var section in sectionOrder)
        {
            if (grouped[section].Count > 0)
                result.Add((section, grouped[section]));
        }

        // Add any sections not in the predefined order
        foreach (var kv in grouped)
        {
            if (!sectionOrder.Contains(kv.Key) && kv.Value.Count > 0)
                result.Add((kv.Key, kv.Value));
        }

        return result;
    }

    private static string ClassifyFunction(string name)
    {
        // Order matters - more specific prefixes first
        if (name.StartsWith("rocksdb_transactiondb_"))
            return "Transaction DB";
        if (name.StartsWith("rocksdb_optimistictransactiondb_"))
            return "Optimistic transaction DB";
        if (name.StartsWith("rocksdb_transaction_"))
            return "Transaction";
        if (name.StartsWith("rocksdb_optimistictransaction_options_") ||
            name.StartsWith("rocksdb_optimistictransactiondb_"))
            return "Optimistic transaction DB";
        if (name.StartsWith("rocksdb_transactiondb_options_"))
            return "Transaction DB";
        if (name.StartsWith("rocksdb_transaction_options_"))
            return "Transaction";

        if (name.StartsWith("rocksdb_writebatch_wi_"))
            return "WriteBatchWi";
        if (name.StartsWith("rocksdb_writebatch_"))
            return "Write batch";

        if (name is "rocksdb_open" or "rocksdb_open_with_ttl" or "rocksdb_open_for_read_only"
            or "rocksdb_open_as_secondary" or "rocksdb_open_column_families"
            or "rocksdb_open_for_read_only_column_families"
            or "rocksdb_open_as_secondary_column_families"
            or "rocksdb_open_and_trim_history"
            or "rocksdb_close" or "rocksdb_destroy_db" or "rocksdb_repair_db"
            or "rocksdb_cancel_all_background_work")
            return "DB open / close";

        if (name.Contains("_column_family") || name.StartsWith("rocksdb_column_family_"))
            return "Column families";
        if (name.StartsWith("rocksdb_list_column_families"))
            return "Column families";
        if (name.StartsWith("rocksdb_create_column_family") || name.StartsWith("rocksdb_drop_column_family"))
            return "Column families";
        if (name.StartsWith("rocksdb_get_default_column_family"))
            return "Column families";

        if (name is "rocksdb_put" or "rocksdb_put_cf"
            or "rocksdb_delete" or "rocksdb_delete_cf"
            or "rocksdb_delete_range_cf"
            or "rocksdb_singledelete" or "rocksdb_singledelete_cf"
            or "rocksdb_merge" or "rocksdb_merge_cf"
            or "rocksdb_write")
            return "Write / Put / Delete / Merge";

        if (name is "rocksdb_get" or "rocksdb_get_cf"
            or "rocksdb_multi_get" or "rocksdb_multi_get_cf"
            or "rocksdb_key_may_exist" or "rocksdb_key_may_exist_cf"
            or "rocksdb_batched_multi_get_cf")
            return "Read / Get";

        if (name.StartsWith("rocksdb_pinnableslice_") || name.StartsWith("rocksdb_get_pinned")
            || name.StartsWith("rocksdb_multi_get_pinned"))
            return "Pinnable slice";

        if (name.Contains("snapshot"))
            return "Snapshot";

        if (name.StartsWith("rocksdb_iter_") || name.StartsWith("rocksdb_create_iterator"))
            return "Iterator";

        if (name.StartsWith("rocksdb_property_"))
            return "Properties";

        if (name.StartsWith("rocksdb_flush") || name.StartsWith("rocksdb_compact_range")
            || name.Contains("file_deletions") || name.Contains("catch_up_with_primary")
            || name.StartsWith("rocksdb_suggest_compact_range"))
            return "Flush / Compact / WAL";

        if (name.StartsWith("rocksdb_readoptions_"))
            return "Read options";
        if (name.StartsWith("rocksdb_writeoptions_"))
            return "Write options";
        if (name.StartsWith("rocksdb_flushoptions_"))
            return "Flush options";
        if (name.StartsWith("rocksdb_compactoptions_"))
            return "Compact options";

        if (name.StartsWith("rocksdb_block_based_options_"))
            return "Block-based table options";
        if (name.StartsWith("rocksdb_cuckoo_options_"))
            return "Cuckoo table options";
        if (name.StartsWith("rocksdb_plain_table_options_") ||
            name.StartsWith("rocksdb_options_set_plain_table_factory"))
            return "Plain table options";

        if (name.StartsWith("rocksdb_options_"))
            return "Options";

        if (name.StartsWith("rocksdb_cache_"))
            return "Cache";
        if (name.StartsWith("rocksdb_filterpolicy_"))
            return "Filter policy";
        if (name.StartsWith("rocksdb_slicetransform_"))
            return "Slice transform";

        if (name.StartsWith("rocksdb_mergeoperator_"))
            return "Merge operator";
        if (name.StartsWith("rocksdb_ratelimiter_"))
            return "Rate limiter";

        if (name.StartsWith("rocksdb_env_") || name.StartsWith("rocksdb_create_default_env")
            || name.StartsWith("rocksdb_create_mem_env"))
            return "Env";
        if (name.StartsWith("rocksdb_envoptions_"))
            return "Env options";

        if (name.StartsWith("rocksdb_sstfilewriter_"))
            return "SST file writer";
        if (name.StartsWith("rocksdb_ingest") || name.StartsWith("rocksdb_ingestexternalfileoptions_"))
            return "Ingest external file";

        if (name.StartsWith("rocksdb_compactionfilter_") && !name.Contains("factory"))
            return "Compaction filter";
        if (name.StartsWith("rocksdb_compactionfiltercontext_"))
            return "Compaction filter";
        if (name.StartsWith("rocksdb_compactionfilterfactory_"))
            return "Compaction filter factory";

        if (name.StartsWith("rocksdb_comparator_"))
            return "Comparator";
        if (name.StartsWith("rocksdb_checkpoint_"))
            return "Checkpoint";

        if (name.StartsWith("rocksdb_backup_engine_") || name.StartsWith("rocksdb_restore_options_"))
            return "Backup engine";

        if (name.StartsWith("rocksdb_logger_"))
            return "Logger";

        if (name.Contains("eventlistener") || name.Contains("flushjobinfo")
            || name.Contains("compactionjobinfo") || name.Contains("subcompactionjobinfo")
            || name.Contains("externalfileingestioninfo") || name.Contains("writestallinfo")
            || name.Contains("memtableinfo") || name.Contains("status_ptr")
            || name.Contains("stall_conditions"))
            return "Event listener";

        if (name.StartsWith("rocksdb_get_db_identity") || name.StartsWith("rocksdb_get_latest_sequence"))
            return "DB identity / sequence number";

        if (name.StartsWith("rocksdb_free") || name.StartsWith("rocksdb_approximate_")
            || name.StartsWith("rocksdb_set_") || name.Contains("livefiles")
            || name.Contains("metadata") || name.StartsWith("rocksdb_delete_file")
            || name.StartsWith("rocksdb_get_column_family_metadata")
            || name == "rocksdb_disable_manual_compaction"
            || name == "rocksdb_enable_manual_compaction"
            || name.StartsWith("rocksdb_perfcontext_")
            || name.StartsWith("rocksdb_write_buffer_manager_")
            || name.StartsWith("rocksdb_dbpath_")
            || name.StartsWith("rocksdb_universal_compaction_")
            || name.StartsWith("rocksdb_fifo_compaction_"))
            return "Status / Utilities";

        return "Miscellaneous";
    }
}
