// <auto-generated>
// This file was generated by NativeMethodsGenerator from RocksDb v11.8.1 statistics.h header.
// https://raw.githubusercontent.com/facebook/rocksdb/v11.8.1/include/rocksdb/statistics.h
// Do not edit manually — re-run the generator to update.
//
// Copyright (c) 2011-present, Facebook, Inc. All rights reserved.
// This source code is licensed under both the GPLv2 (found in the
// COPYING file in the root directory) and Apache 2.0 License
// (found in the LICENSE.Apache file in the root directory).
//
// Those two files live in RocksDb's repository, at
// https://github.com/facebook/rocksdb, not in this one. A copy of the
// Apache 2.0 text ships with this package under licenses/.
//
// Modified from the original: the C++ enum members have been renamed to
// this library's casing and their comments reproduced as XML
// documentation. The numeric values are RocksDb's own. No RocksDb
// implementation code is included or reproduced here.
// </auto-generated>

namespace RocksDbNet;

/// <summary>
/// A counter collected by the statistics subsystem.
/// </summary>
/// <remarks>
/// Pass one to <see cref="DbOptions.GetTickerCount(Ticker)"/>. Every counter is cumulative for the life of the statistics object.
/// <para>
/// The values are positional in RocksDb's header, so they change between
/// releases when a counter is added or retired. They are generated from the
/// pinned version rather than written out by hand for that reason.
/// </para>
/// </remarks>
public enum Ticker
{
    /// <summary>
    /// total block cache misses REQUIRES: BLOCK_CACHE_MISS == BLOCK_CACHE_INDEX_MISS + BLOCK_CACHE_FILTER_MISS + BLOCK_CACHE_DATA_MISS;
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_MISS</c>.</remarks>
    BlockCacheMiss = 0,

    /// <summary>
    /// total block cache hit REQUIRES: BLOCK_CACHE_HIT == BLOCK_CACHE_INDEX_HIT + BLOCK_CACHE_FILTER_HIT + BLOCK_CACHE_DATA_HIT;
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_HIT</c>.</remarks>
    BlockCacheHit = 1,

    /// <summary>
    /// # of blocks added to block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_ADD</c>.</remarks>
    BlockCacheAdd = 2,

    /// <summary>
    /// # of failures when adding blocks to block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_ADD_FAILURES</c>.</remarks>
    BlockCacheAddFailures = 3,

    /// <summary>
    /// # of times cache miss when accessing index block from block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_INDEX_MISS</c>.</remarks>
    BlockCacheIndexMiss = 4,

    /// <summary>
    /// # of times cache hit when accessing index block from block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_INDEX_HIT</c>.</remarks>
    BlockCacheIndexHit = 5,

    /// <summary>
    /// # of index blocks added to block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_INDEX_ADD</c>.</remarks>
    BlockCacheIndexAdd = 6,

    /// <summary>
    /// # of bytes of index blocks inserted into cache
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_INDEX_BYTES_INSERT</c>.</remarks>
    BlockCacheIndexBytesInsert = 7,

    /// <summary>
    /// # of times cache miss when accessing filter block from block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_FILTER_MISS</c>.</remarks>
    BlockCacheFilterMiss = 8,

    /// <summary>
    /// # of times cache hit when accessing filter block from block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_FILTER_HIT</c>.</remarks>
    BlockCacheFilterHit = 9,

    /// <summary>
    /// # of filter blocks added to block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_FILTER_ADD</c>.</remarks>
    BlockCacheFilterAdd = 10,

    /// <summary>
    /// # of bytes of bloom filter blocks inserted into cache
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_FILTER_BYTES_INSERT</c>.</remarks>
    BlockCacheFilterBytesInsert = 11,

    /// <summary>
    /// # of times cache miss when accessing data block from block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_DATA_MISS</c>.</remarks>
    BlockCacheDataMiss = 12,

    /// <summary>
    /// # of times cache hit when accessing data block from block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_DATA_HIT</c>.</remarks>
    BlockCacheDataHit = 13,

    /// <summary>
    /// # of data blocks added to block cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_DATA_ADD</c>.</remarks>
    BlockCacheDataAdd = 14,

    /// <summary>
    /// # of bytes of data blocks inserted into cache
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_DATA_BYTES_INSERT</c>.</remarks>
    BlockCacheDataBytesInsert = 15,

    /// <summary>
    /// # of bytes read from cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_BYTES_READ</c>.</remarks>
    BlockCacheBytesRead = 16,

    /// <summary>
    /// # of bytes written into cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_BYTES_WRITE</c>.</remarks>
    BlockCacheBytesWrite = 17,

    /// <summary>
    /// RocksDb's <c>BLOCK_CACHE_COMPRESSION_DICT_MISS</c>.
    /// </summary>
    BlockCacheCompressionDictMiss = 18,

    /// <summary>
    /// RocksDb's <c>BLOCK_CACHE_COMPRESSION_DICT_HIT</c>.
    /// </summary>
    BlockCacheCompressionDictHit = 19,

    /// <summary>
    /// RocksDb's <c>BLOCK_CACHE_COMPRESSION_DICT_ADD</c>.
    /// </summary>
    BlockCacheCompressionDictAdd = 20,

    /// <summary>
    /// RocksDb's <c>BLOCK_CACHE_COMPRESSION_DICT_BYTES_INSERT</c>.
    /// </summary>
    BlockCacheCompressionDictBytesInsert = 21,

    /// <summary>
    /// # of blocks redundantly inserted into block cache. REQUIRES: BLOCK_CACHE_ADD_REDUNDANT &lt;= BLOCK_CACHE_ADD
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_ADD_REDUNDANT</c>.</remarks>
    BlockCacheAddRedundant = 22,

    /// <summary>
    /// # of index blocks redundantly inserted into block cache. REQUIRES: BLOCK_CACHE_INDEX_ADD_REDUNDANT &lt;= BLOCK_CACHE_INDEX_ADD
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_INDEX_ADD_REDUNDANT</c>.</remarks>
    BlockCacheIndexAddRedundant = 23,

    /// <summary>
    /// # of filter blocks redundantly inserted into block cache. REQUIRES: BLOCK_CACHE_FILTER_ADD_REDUNDANT &lt;= BLOCK_CACHE_FILTER_ADD
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_FILTER_ADD_REDUNDANT</c>.</remarks>
    BlockCacheFilterAddRedundant = 24,

    /// <summary>
    /// # of data blocks redundantly inserted into block cache. REQUIRES: BLOCK_CACHE_DATA_ADD_REDUNDANT &lt;= BLOCK_CACHE_DATA_ADD
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_DATA_ADD_REDUNDANT</c>.</remarks>
    BlockCacheDataAddRedundant = 25,

    /// <summary>
    /// # of dict blocks redundantly inserted into block cache. REQUIRES: BLOCK_CACHE_COMPRESSION_DICT_ADD_REDUNDANT &lt;= BLOCK_CACHE_COMPRESSION_DICT_ADD
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CACHE_COMPRESSION_DICT_ADD_REDUNDANT</c>.</remarks>
    BlockCacheCompressionDictAddRedundant = 26,

    /// <summary>
    /// Secondary cache statistics
    /// </summary>
    /// <remarks>RocksDb calls this <c>SECONDARY_CACHE_HITS</c>.</remarks>
    SecondaryCacheHits = 27,

    /// <summary>
    /// Fine grained secondary cache stats
    /// </summary>
    /// <remarks>RocksDb calls this <c>SECONDARY_CACHE_FILTER_HITS</c>.</remarks>
    SecondaryCacheFilterHits = 28,

    /// <summary>
    /// RocksDb's <c>SECONDARY_CACHE_INDEX_HITS</c>.
    /// </summary>
    SecondaryCacheIndexHits = 29,

    /// <summary>
    /// RocksDb's <c>SECONDARY_CACHE_DATA_HITS</c>.
    /// </summary>
    SecondaryCacheDataHits = 30,

    /// <summary>
    /// Compressed secondary cache related stats
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPRESSED_SECONDARY_CACHE_DUMMY_HITS</c>.</remarks>
    CompressedSecondaryCacheDummyHits = 31,

    /// <summary>
    /// RocksDb's <c>COMPRESSED_SECONDARY_CACHE_HITS</c>.
    /// </summary>
    CompressedSecondaryCacheHits = 32,

    /// <summary>
    /// RocksDb's <c>COMPRESSED_SECONDARY_CACHE_PROMOTIONS</c>.
    /// </summary>
    CompressedSecondaryCachePromotions = 33,

    /// <summary>
    /// RocksDb's <c>COMPRESSED_SECONDARY_CACHE_PROMOTION_SKIPS</c>.
    /// </summary>
    CompressedSecondaryCachePromotionSkips = 34,

    /// <summary>
    /// # of times bloom filter has avoided file reads, i.e., negatives.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOOM_FILTER_USEFUL</c>.</remarks>
    BloomFilterUseful = 35,

    /// <summary>
    /// # of times bloom FullFilter has not avoided the reads.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOOM_FILTER_FULL_POSITIVE</c>.</remarks>
    BloomFilterFullPositive = 36,

    /// <summary>
    /// # of times bloom FullFilter has not avoided the reads and data actually exist.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOOM_FILTER_FULL_TRUE_POSITIVE</c>.</remarks>
    BloomFilterFullTruePositive = 37,

    /// <summary>
    /// Prefix filter stats when used for point lookups (Get / MultiGet). (For prefix filter stats on iterators, see *_LEVEL_SEEK_*.) Checked: filter was queried
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOOM_FILTER_PREFIX_CHECKED</c>.</remarks>
    BloomFilterPrefixChecked = 38,

    /// <summary>
    /// Useful: filter returned false so prevented accessing data+index blocks
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOOM_FILTER_PREFIX_USEFUL</c>.</remarks>
    BloomFilterPrefixUseful = 39,

    /// <summary>
    /// True positive: found a key matching the point query. When another key with the same prefix matches, it is considered a false positive by these statistics even though the filter returned a true positive.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOOM_FILTER_PREFIX_TRUE_POSITIVE</c>.</remarks>
    BloomFilterPrefixTruePositive = 40,

    /// <summary>
    /// # persistent cache hit
    /// </summary>
    /// <remarks>RocksDb calls this <c>PERSISTENT_CACHE_HIT</c>.</remarks>
    PersistentCacheHit = 41,

    /// <summary>
    /// # persistent cache miss
    /// </summary>
    /// <remarks>RocksDb calls this <c>PERSISTENT_CACHE_MISS</c>.</remarks>
    PersistentCacheMiss = 42,

    /// <summary>
    /// # total simulation block cache hits
    /// </summary>
    /// <remarks>RocksDb calls this <c>SIM_BLOCK_CACHE_HIT</c>.</remarks>
    SimBlockCacheHit = 43,

    /// <summary>
    /// # total simulation block cache misses
    /// </summary>
    /// <remarks>RocksDb calls this <c>SIM_BLOCK_CACHE_MISS</c>.</remarks>
    SimBlockCacheMiss = 44,

    /// <summary>
    /// # of memtable hits.
    /// </summary>
    /// <remarks>RocksDb calls this <c>MEMTABLE_HIT</c>.</remarks>
    MemtableHit = 45,

    /// <summary>
    /// # of memtable misses.
    /// </summary>
    /// <remarks>RocksDb calls this <c>MEMTABLE_MISS</c>.</remarks>
    MemtableMiss = 46,

    /// <summary>
    /// # of Get() queries served by L0
    /// </summary>
    /// <remarks>RocksDb calls this <c>GET_HIT_L0</c>.</remarks>
    GetHitL0 = 47,

    /// <summary>
    /// # of Get() queries served by L1
    /// </summary>
    /// <remarks>RocksDb calls this <c>GET_HIT_L1</c>.</remarks>
    GetHitL1 = 48,

    /// <summary>
    /// # of Get() queries served by L2 and up
    /// </summary>
    /// <remarks>RocksDb calls this <c>GET_HIT_L2_AND_UP</c>.</remarks>
    GetHitL2AndUp = 49,

    /// <summary>
    /// COMPACTION_KEY_DROP_* count the reasons for key drop during compaction There are 4 reasons currently. key was written with a newer value. Also includes keys dropped for range del.
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACTION_KEY_DROP_NEWER_ENTRY</c>.</remarks>
    CompactionKeyDropNewerEntry = 50,

    /// <summary>
    /// The key is obsolete.
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACTION_KEY_DROP_OBSOLETE</c>.</remarks>
    CompactionKeyDropObsolete = 51,

    /// <summary>
    /// key was covered by a range tombstone.
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACTION_KEY_DROP_RANGE_DEL</c>.</remarks>
    CompactionKeyDropRangeDel = 52,

    /// <summary>
    /// user compaction function has dropped the key.
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACTION_KEY_DROP_USER</c>.</remarks>
    CompactionKeyDropUser = 53,

    /// <summary>
    /// all keys in range were deleted. Deletions obsoleted before bottom level due to file gap optimization.
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACTION_RANGE_DEL_DROP_OBSOLETE</c>.</remarks>
    CompactionRangeDelDropObsolete = 54,

    /// <summary>
    /// RocksDb's <c>COMPACTION_OPTIMIZED_DEL_DROP_OBSOLETE</c>.
    /// </summary>
    CompactionOptimizedDelDropObsolete = 55,

    /// <summary>
    /// If a compaction was canceled in sfm to prevent ENOSPC
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACTION_CANCELLED</c>.</remarks>
    CompactionCancelled = 56,

    /// <summary>
    /// Number of compactions aborted via AbortAllCompactions()
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACTION_ABORTED</c>.</remarks>
    CompactionAborted = 57,

    /// <summary>
    /// Number of keys written to the database via the Put and Write call&apos;s
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_KEYS_WRITTEN</c>.</remarks>
    NumberKeysWritten = 58,

    /// <summary>
    /// Number of Keys read,
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_KEYS_READ</c>.</remarks>
    NumberKeysRead = 59,

    /// <summary>
    /// Number keys updated, if inplace update is enabled
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_KEYS_UPDATED</c>.</remarks>
    NumberKeysUpdated = 60,

    /// <summary>
    /// The number of uncompressed bytes issued by DB::Put(), DB::Delete(), DB::Merge(), and DB::Write().
    /// </summary>
    /// <remarks>RocksDb calls this <c>BYTES_WRITTEN</c>.</remarks>
    BytesWritten = 61,

    /// <summary>
    /// The number of uncompressed bytes read from DB::Get().  It could be either from memtables, cache, or table files. For the number of logical bytes read from DB::MultiGet(), please use NUMBER_MULTIGET_BYTES_READ.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BYTES_READ</c>.</remarks>
    BytesRead = 62,

    /// <summary>
    /// The number of calls to seek/next/prev
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_DB_SEEK</c>.</remarks>
    NumberDbSeek = 63,

    /// <summary>
    /// RocksDb's <c>NUMBER_DB_NEXT</c>.
    /// </summary>
    NumberDbNext = 64,

    /// <summary>
    /// RocksDb's <c>NUMBER_DB_PREV</c>.
    /// </summary>
    NumberDbPrev = 65,

    /// <summary>
    /// The number of calls to seek/next/prev that returned data
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_DB_SEEK_FOUND</c>.</remarks>
    NumberDbSeekFound = 66,

    /// <summary>
    /// RocksDb's <c>NUMBER_DB_NEXT_FOUND</c>.
    /// </summary>
    NumberDbNextFound = 67,

    /// <summary>
    /// RocksDb's <c>NUMBER_DB_PREV_FOUND</c>.
    /// </summary>
    NumberDbPrevFound = 68,

    /// <summary>
    /// The number of uncompressed bytes read from an iterator. Includes size of key and value.
    /// </summary>
    /// <remarks>RocksDb calls this <c>ITER_BYTES_READ</c>.</remarks>
    IterBytesRead = 69,

    /// <summary>
    /// Number of internal keys skipped by Iterator
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_ITER_SKIP</c>.</remarks>
    NumberIterSkip = 70,

    /// <summary>
    /// Number of times we had to reseek inside an iteration to skip over large number of keys with same userkey.
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_OF_RESEEKS_IN_ITERATION</c>.</remarks>
    NumberOfReseeksInIteration = 71,

    /// <summary>
    /// number of iterators created
    /// </summary>
    /// <remarks>RocksDb calls this <c>NO_ITERATOR_CREATED</c>.</remarks>
    NoIteratorCreated = 72,

    /// <summary>
    /// number of iterators deleted
    /// </summary>
    /// <remarks>RocksDb calls this <c>NO_ITERATOR_DELETED</c>.</remarks>
    NoIteratorDeleted = 73,

    /// <summary>
    /// RocksDb's <c>NO_FILE_OPENS</c>.
    /// </summary>
    NoFileOpens = 74,

    /// <summary>
    /// RocksDb's <c>NO_FILE_ERRORS</c>.
    /// </summary>
    NoFileErrors = 75,

    /// <summary>
    /// Writer has to wait for compaction or flush to finish.
    /// </summary>
    /// <remarks>RocksDb calls this <c>STALL_MICROS</c>.</remarks>
    StallMicros = 76,

    /// <summary>
    /// The wait time for db mutex. Disabled by default. To enable it set stats level to kAll
    /// </summary>
    /// <remarks>RocksDb calls this <c>DB_MUTEX_WAIT_MICROS</c>.</remarks>
    DbMutexWaitMicros = 77,

    /// <summary>
    /// Number of MultiGet calls, keys read, and bytes read
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_MULTIGET_CALLS</c>.</remarks>
    NumberMultigetCalls = 78,

    /// <summary>
    /// RocksDb's <c>NUMBER_MULTIGET_KEYS_READ</c>.
    /// </summary>
    NumberMultigetKeysRead = 79,

    /// <summary>
    /// RocksDb's <c>NUMBER_MULTIGET_BYTES_READ</c>.
    /// </summary>
    NumberMultigetBytesRead = 80,

    /// <summary>
    /// Number of keys actually found in MultiGet calls (vs number requested by caller) NUMBER_MULTIGET_KEYS_READ gives the number requested by caller
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_MULTIGET_KEYS_FOUND</c>.</remarks>
    NumberMultigetKeysFound = 81,

    /// <summary>
    /// RocksDb's <c>NUMBER_MERGE_FAILURES</c>.
    /// </summary>
    NumberMergeFailures = 82,

    /// <summary>
    /// Record the number of calls to GetUpdatesSince. Useful to keep track of transaction log iterator refreshes
    /// </summary>
    /// <remarks>RocksDb calls this <c>GET_UPDATES_SINCE_CALLS</c>.</remarks>
    GetUpdatesSinceCalls = 83,

    /// <summary>
    /// Number of times WAL sync is done
    /// </summary>
    /// <remarks>RocksDb calls this <c>WAL_FILE_SYNCED</c>.</remarks>
    WalFileSynced = 84,

    /// <summary>
    /// Number of bytes written to WAL Number of WAL rotations that consumed an async precreated WAL.
    /// </summary>
    /// <remarks>RocksDb calls this <c>WAL_FILE_BYTES</c>.</remarks>
    WalFileBytes = 85,

    /// <summary>
    /// RocksDb's <c>WAL_PRECREATE_HIT</c>.
    /// </summary>
    WalPrecreateHit = 86,

    /// <summary>
    /// Number of WAL rotations that found no async precreated WAL to consume.
    /// </summary>
    /// <remarks>RocksDb calls this <c>WAL_PRECREATE_MISS</c>.</remarks>
    WalPrecreateMiss = 87,

    /// <summary>
    /// Number of WAL rotations that waited for an in-flight WAL precreation.
    /// </summary>
    /// <remarks>RocksDb calls this <c>WAL_PRECREATE_WAITED</c>.</remarks>
    WalPrecreateWaited = 88,

    /// <summary>
    /// Total foreground wait time for in-flight WAL precreation.
    /// </summary>
    /// <remarks>RocksDb calls this <c>WAL_PRECREATE_WAIT_MICROS</c>.</remarks>
    WalPrecreateWaitMicros = 89,

    /// <summary>
    /// Number of async WAL precreation attempts that failed.
    /// </summary>
    /// <remarks>RocksDb calls this <c>WAL_PRECREATE_FAILED</c>.</remarks>
    WalPrecreateFailed = 90,

    /// <summary>
    /// Writes can be processed by requesting thread or by the thread at the head of the writers queue.
    /// </summary>
    /// <remarks>RocksDb calls this <c>WRITE_DONE_BY_SELF</c>.</remarks>
    WriteDoneBySelf = 91,

    /// <summary>
    /// Equivalent to writes done for others
    /// </summary>
    /// <remarks>RocksDb calls this <c>WRITE_DONE_BY_OTHER</c>.</remarks>
    WriteDoneByOther = 92,

    /// <summary>
    /// Number of Write calls that request WAL
    /// </summary>
    /// <remarks>RocksDb calls this <c>WRITE_WITH_WAL</c>.</remarks>
    WriteWithWal = 93,

    /// <summary>
    /// Bytes read during compaction
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACT_READ_BYTES</c>.</remarks>
    CompactReadBytes = 94,

    /// <summary>
    /// Bytes written during compaction
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACT_WRITE_BYTES</c>.</remarks>
    CompactWriteBytes = 95,

    /// <summary>
    /// Bytes written during flush
    /// </summary>
    /// <remarks>RocksDb calls this <c>FLUSH_WRITE_BYTES</c>.</remarks>
    FlushWriteBytes = 96,

    /// <summary>
    /// Compaction read and write statistics broken down by CompactionReason
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACT_READ_BYTES_MARKED</c>.</remarks>
    CompactReadBytesMarked = 97,

    /// <summary>
    /// RocksDb's <c>COMPACT_READ_BYTES_PERIODIC</c>.
    /// </summary>
    CompactReadBytesPeriodic = 98,

    /// <summary>
    /// RocksDb's <c>COMPACT_READ_BYTES_TTL</c>.
    /// </summary>
    CompactReadBytesTtl = 99,

    /// <summary>
    /// RocksDb's <c>COMPACT_WRITE_BYTES_MARKED</c>.
    /// </summary>
    CompactWriteBytesMarked = 100,

    /// <summary>
    /// RocksDb's <c>COMPACT_WRITE_BYTES_PERIODIC</c>.
    /// </summary>
    CompactWriteBytesPeriodic = 101,

    /// <summary>
    /// RocksDb's <c>COMPACT_WRITE_BYTES_TTL</c>.
    /// </summary>
    CompactWriteBytesTtl = 102,

    /// <summary>
    /// Number of table&apos;s properties loaded directly from file, without creating table reader object.
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_DIRECT_LOAD_TABLE_PROPERTIES</c>.</remarks>
    NumberDirectLoadTableProperties = 103,

    /// <summary>
    /// RocksDb's <c>NUMBER_SUPERVERSION_ACQUIRES</c>.
    /// </summary>
    NumberSuperversionAcquires = 104,

    /// <summary>
    /// RocksDb's <c>NUMBER_SUPERVERSION_RELEASES</c>.
    /// </summary>
    NumberSuperversionReleases = 105,

    /// <summary>
    /// RocksDb's <c>NUMBER_SUPERVERSION_CLEANUPS</c>.
    /// </summary>
    NumberSuperversionCleanups = 106,

    /// <summary>
    /// # of compressions/decompressions executed
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_BLOCK_COMPRESSED</c>.</remarks>
    NumberBlockCompressed = 107,

    /// <summary>
    /// RocksDb's <c>NUMBER_BLOCK_DECOMPRESSED</c>.
    /// </summary>
    NumberBlockDecompressed = 108,

    /// <summary>
    /// Number of input bytes (uncompressed) to compression for SST blocks that are stored compressed.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BYTES_COMPRESSED_FROM</c>.</remarks>
    BytesCompressedFrom = 109,

    /// <summary>
    /// Number of output bytes (compressed) from compression for SST blocks that are stored compressed.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BYTES_COMPRESSED_TO</c>.</remarks>
    BytesCompressedTo = 110,

    /// <summary>
    /// Number of uncompressed bytes for SST blocks that are stored uncompressed because compression type is kNoCompression, or some error case caused compression not to run or produce an output. Index blocks are only counted if enable_index_compression is true.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BYTES_COMPRESSION_BYPASSED</c>.</remarks>
    BytesCompressionBypassed = 111,

    /// <summary>
    /// Number of input bytes (uncompressed) to compression for SST blocks that are stored uncompressed because the compression result was rejected, either because the ratio was not acceptable (see CompressionOptions::max_compressed_bytes_per_kb) or found invalid by the `verify_compression` option.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BYTES_COMPRESSION_REJECTED</c>.</remarks>
    BytesCompressionRejected = 112,

    /// <summary>
    /// Like BYTES_COMPRESSION_BYPASSED but counting number of blocks
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_BLOCK_COMPRESSION_BYPASSED</c>.</remarks>
    NumberBlockCompressionBypassed = 113,

    /// <summary>
    /// Like BYTES_COMPRESSION_REJECTED but counting number of blocks
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_BLOCK_COMPRESSION_REJECTED</c>.</remarks>
    NumberBlockCompressionRejected = 114,

    /// <summary>
    /// Number of input bytes (compressed) to decompression in reading compressed SST blocks from storage.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BYTES_DECOMPRESSED_FROM</c>.</remarks>
    BytesDecompressedFrom = 115,

    /// <summary>
    /// Number of output bytes (uncompressed) from decompression in reading compressed SST blocks from storage.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BYTES_DECOMPRESSED_TO</c>.</remarks>
    BytesDecompressedTo = 116,

    /// <summary>
    /// Tickers that record cumulative time.
    /// </summary>
    /// <remarks>RocksDb calls this <c>MERGE_OPERATION_TOTAL_TIME</c>.</remarks>
    MergeOperationTotalTime = 117,

    /// <summary>
    /// RocksDb's <c>FILTER_OPERATION_TOTAL_TIME</c>.
    /// </summary>
    FilterOperationTotalTime = 118,

    /// <summary>
    /// RocksDb's <c>COMPACTION_CPU_TOTAL_TIME</c>.
    /// </summary>
    CompactionCpuTotalTime = 119,

    /// <summary>
    /// Row cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>ROW_CACHE_HIT</c>.</remarks>
    RowCacheHit = 120,

    /// <summary>
    /// RocksDb's <c>ROW_CACHE_MISS</c>.
    /// </summary>
    RowCacheMiss = 121,

    /// <summary>
    /// Read amplification statistics. Read amplification can be calculated using this formula (READ_AMP_TOTAL_READ_BYTES / READ_AMP_ESTIMATE_USEFUL_BYTES) REQUIRES: ReadOptions::read_amp_bytes_per_bit to be enabled Estimate of total bytes actually used.
    /// </summary>
    /// <remarks>RocksDb calls this <c>READ_AMP_ESTIMATE_USEFUL_BYTES</c>.</remarks>
    ReadAmpEstimateUsefulBytes = 122,

    /// <summary>
    /// Total size of loaded data blocks.
    /// </summary>
    /// <remarks>RocksDb calls this <c>READ_AMP_TOTAL_READ_BYTES</c>.</remarks>
    ReadAmpTotalReadBytes = 123,

    /// <summary>
    /// Number of refill intervals where rate limiter&apos;s bytes are fully consumed.
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_RATE_LIMITER_DRAINS</c>.</remarks>
    NumberRateLimiterDrains = 124,

    /// <summary>
    /// Bytes granted by the rate limiter for read requests.
    /// </summary>
    /// <remarks>RocksDb calls this <c>RATE_LIMITER_BYTES_READ</c>.</remarks>
    RateLimiterBytesRead = 125,

    /// <summary>
    /// Bytes granted by the rate limiter for write requests.
    /// </summary>
    /// <remarks>RocksDb calls this <c>RATE_LIMITER_BYTES_WRITE</c>.</remarks>
    RateLimiterBytesWrite = 126,

    /// <summary>
    /// Number of read requests granted by the rate limiter.
    /// </summary>
    /// <remarks>RocksDb calls this <c>RATE_LIMITER_REQUESTS_READ</c>.</remarks>
    RateLimiterRequestsRead = 127,

    /// <summary>
    /// Number of write requests granted by the rate limiter.
    /// </summary>
    /// <remarks>RocksDb calls this <c>RATE_LIMITER_REQUESTS_WRITE</c>.</remarks>
    RateLimiterRequestsWrite = 128,

    /// <summary>
    /// Number of read requests that waited for a future rate limiter refill.
    /// </summary>
    /// <remarks>RocksDb calls this <c>RATE_LIMITER_DELAYED_REQUESTS_READ</c>.</remarks>
    RateLimiterDelayedRequestsRead = 129,

    /// <summary>
    /// Number of write requests that waited for a future rate limiter refill.
    /// </summary>
    /// <remarks>RocksDb calls this <c>RATE_LIMITER_DELAYED_REQUESTS_WRITE</c>.</remarks>
    RateLimiterDelayedRequestsWrite = 130,

    /// <summary>
    /// Total time read requests spent waiting for rate limiter refills.
    /// </summary>
    /// <remarks>RocksDb calls this <c>RATE_LIMITER_TOTAL_WAIT_MICROS_READ</c>.</remarks>
    RateLimiterTotalWaitMicrosRead = 131,

    /// <summary>
    /// Total time write requests spent waiting for rate limiter refills.
    /// </summary>
    /// <remarks>RocksDb calls this <c>RATE_LIMITER_TOTAL_WAIT_MICROS_WRITE</c>.</remarks>
    RateLimiterTotalWaitMicrosWrite = 132,

    /// <summary>
    /// BlobDB specific stats # of Put/PutWithTTL to BlobDB. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_NUM_PUT</c>.</remarks>
    BlobDbNumPut = 133,

    /// <summary>
    /// # of Write to BlobDB. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_NUM_WRITE</c>.</remarks>
    BlobDbNumWrite = 134,

    /// <summary>
    /// # of Get to BlobDB. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_NUM_GET</c>.</remarks>
    BlobDbNumGet = 135,

    /// <summary>
    /// # of MultiGet to BlobDB. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_NUM_MULTIGET</c>.</remarks>
    BlobDbNumMultiget = 136,

    /// <summary>
    /// # of Seek/SeekToFirst/SeekToLast/SeekForPrev to BlobDB iterator. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_NUM_SEEK</c>.</remarks>
    BlobDbNumSeek = 137,

    /// <summary>
    /// # of Next to BlobDB iterator. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_NUM_NEXT</c>.</remarks>
    BlobDbNumNext = 138,

    /// <summary>
    /// # of Prev to BlobDB iterator. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_NUM_PREV</c>.</remarks>
    BlobDbNumPrev = 139,

    /// <summary>
    /// # of keys written to BlobDB. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_NUM_KEYS_WRITTEN</c>.</remarks>
    BlobDbNumKeysWritten = 140,

    /// <summary>
    /// # of keys read from BlobDB. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_NUM_KEYS_READ</c>.</remarks>
    BlobDbNumKeysRead = 141,

    /// <summary>
    /// # of bytes (key + value) written to BlobDB. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BYTES_WRITTEN</c>.</remarks>
    BlobDbBytesWritten = 142,

    /// <summary>
    /// # of bytes (keys + value) read from BlobDB. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BYTES_READ</c>.</remarks>
    BlobDbBytesRead = 143,

    /// <summary>
    /// Deprecated: min_blob_size is no longer configurable. Retained to avoid shifting enum values.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_WRITE_INLINED_DEPRECATED</c>.</remarks>
    BlobDbWriteInlinedDeprecated = 144,

    /// <summary>
    /// Deprecated: min_blob_size is no longer configurable. Retained to avoid shifting enum values.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_WRITE_INLINED_TTL_DEPRECATED</c>.</remarks>
    BlobDbWriteInlinedTtlDeprecated = 145,

    /// <summary>
    /// # of keys written by BlobDB as non-TTL blob value. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_WRITE_BLOB</c>.</remarks>
    BlobDbWriteBlob = 146,

    /// <summary>
    /// # of keys written by BlobDB as TTL blob value. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_WRITE_BLOB_TTL</c>.</remarks>
    BlobDbWriteBlobTtl = 147,

    /// <summary>
    /// # of bytes written to blob file.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BLOB_FILE_BYTES_WRITTEN</c>.</remarks>
    BlobDbBlobFileBytesWritten = 148,

    /// <summary>
    /// # of bytes read from blob file.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BLOB_FILE_BYTES_READ</c>.</remarks>
    BlobDbBlobFileBytesRead = 149,

    /// <summary>
    /// # of times a blob files being synced.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BLOB_FILE_SYNCED</c>.</remarks>
    BlobDbBlobFileSynced = 150,

    /// <summary>
    /// # of blob index evicted from base DB by BlobDB compaction filter because of expiration. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BLOB_INDEX_EXPIRED_COUNT</c>.</remarks>
    BlobDbBlobIndexExpiredCount = 151,

    /// <summary>
    /// size of blob index evicted from base DB by BlobDB compaction filter because of expiration. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BLOB_INDEX_EXPIRED_SIZE</c>.</remarks>
    BlobDbBlobIndexExpiredSize = 152,

    /// <summary>
    /// # of blob index evicted from base DB by BlobDB compaction filter because of corresponding file deleted. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BLOB_INDEX_EVICTED_COUNT</c>.</remarks>
    BlobDbBlobIndexEvictedCount = 153,

    /// <summary>
    /// size of blob index evicted from base DB by BlobDB compaction filter because of corresponding file deleted. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BLOB_INDEX_EVICTED_SIZE</c>.</remarks>
    BlobDbBlobIndexEvictedSize = 154,

    /// <summary>
    /// # of blob files that were obsoleted by garbage collection. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_GC_NUM_FILES</c>.</remarks>
    BlobDbGcNumFiles = 155,

    /// <summary>
    /// # of blob files generated by garbage collection. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_GC_NUM_NEW_FILES</c>.</remarks>
    BlobDbGcNumNewFiles = 156,

    /// <summary>
    /// # of BlobDB garbage collection failures. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_GC_FAILURES</c>.</remarks>
    BlobDbGcFailures = 157,

    /// <summary>
    /// # of keys relocated to new blob file by garbage collection.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_GC_NUM_KEYS_RELOCATED</c>.</remarks>
    BlobDbGcNumKeysRelocated = 158,

    /// <summary>
    /// # of bytes relocated to new blob file by garbage collection.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_GC_BYTES_RELOCATED</c>.</remarks>
    BlobDbGcBytesRelocated = 159,

    /// <summary>
    /// # of blob files evicted because of BlobDB is full. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_FIFO_NUM_FILES_EVICTED</c>.</remarks>
    BlobDbFifoNumFilesEvicted = 160,

    /// <summary>
    /// # of keys in the blob files evicted because of BlobDB is full. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_FIFO_NUM_KEYS_EVICTED</c>.</remarks>
    BlobDbFifoNumKeysEvicted = 161,

    /// <summary>
    /// # of bytes in the blob files evicted because of BlobDB is full. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_FIFO_BYTES_EVICTED</c>.</remarks>
    BlobDbFifoBytesEvicted = 162,

    /// <summary>
    /// Integrated BlobDB specific stats # of times cache miss when accessing blob from blob cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_CACHE_MISS</c>.</remarks>
    BlobDbCacheMiss = 163,

    /// <summary>
    /// # of times cache hit when accessing blob from blob cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_CACHE_HIT</c>.</remarks>
    BlobDbCacheHit = 164,

    /// <summary>
    /// # of data blocks added to blob cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_CACHE_ADD</c>.</remarks>
    BlobDbCacheAdd = 165,

    /// <summary>
    /// # of failures when adding blobs to blob cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_CACHE_ADD_FAILURES</c>.</remarks>
    BlobDbCacheAddFailures = 166,

    /// <summary>
    /// # of bytes read from blob cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_CACHE_BYTES_READ</c>.</remarks>
    BlobDbCacheBytesRead = 167,

    /// <summary>
    /// # of bytes written into blob cache.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_CACHE_BYTES_WRITE</c>.</remarks>
    BlobDbCacheBytesWrite = 168,

    /// <summary>
    /// These counters indicate a performance issue in WritePrepared transactions. We should not seem them ticking them much. # of times prepare_mutex_ is acquired in the fast path.
    /// </summary>
    /// <remarks>RocksDb calls this <c>TXN_PREPARE_MUTEX_OVERHEAD</c>.</remarks>
    TxnPrepareMutexOverhead = 169,

    /// <summary>
    /// # of times old_commit_map_mutex_ is acquired in the fast path.
    /// </summary>
    /// <remarks>RocksDb calls this <c>TXN_OLD_COMMIT_MAP_MUTEX_OVERHEAD</c>.</remarks>
    TxnOldCommitMapMutexOverhead = 170,

    /// <summary>
    /// # of times we checked a batch for duplicate keys.
    /// </summary>
    /// <remarks>RocksDb calls this <c>TXN_DUPLICATE_KEY_OVERHEAD</c>.</remarks>
    TxnDuplicateKeyOverhead = 171,

    /// <summary>
    /// # of times snapshot_mutex_ is acquired in the fast path.
    /// </summary>
    /// <remarks>RocksDb calls this <c>TXN_SNAPSHOT_MUTEX_OVERHEAD</c>.</remarks>
    TxnSnapshotMutexOverhead = 172,

    /// <summary>
    /// # of times ::Get returned TryAgain due to expired snapshot seq
    /// </summary>
    /// <remarks>RocksDb calls this <c>TXN_GET_TRY_AGAIN</c>.</remarks>
    TxnGetTryAgain = 173,

    /// <summary>
    /// # of files marked as trash by sst file manager and will be deleted later by background thread.
    /// </summary>
    /// <remarks>RocksDb calls this <c>FILES_MARKED_TRASH</c>.</remarks>
    FilesMarkedTrash = 174,

    /// <summary>
    /// # of trash files deleted by the background thread from the trash queue.
    /// </summary>
    /// <remarks>RocksDb calls this <c>FILES_DELETED_FROM_TRASH_QUEUE</c>.</remarks>
    FilesDeletedFromTrashQueue = 175,

    /// <summary>
    /// # of files deleted immediately by sst file manager through delete scheduler.
    /// </summary>
    /// <remarks>RocksDb calls this <c>FILES_DELETED_IMMEDIATELY</c>.</remarks>
    FilesDeletedImmediately = 176,

    /// <summary>
    /// The counters for error handler, note that, bg_io_error is the subset of bg_error and bg_retryable_io_error is the subset of bg_io_error.
    /// </summary>
    /// <remarks>RocksDb calls this <c>ERROR_HANDLER_BG_ERROR_COUNT</c>.</remarks>
    ErrorHandlerBgErrorCount = 177,

    /// <summary>
    /// RocksDb's <c>ERROR_HANDLER_BG_IO_ERROR_COUNT</c>.
    /// </summary>
    ErrorHandlerBgIoErrorCount = 178,

    /// <summary>
    /// RocksDb's <c>ERROR_HANDLER_BG_RETRYABLE_IO_ERROR_COUNT</c>.
    /// </summary>
    ErrorHandlerBgRetryableIoErrorCount = 179,

    /// <summary>
    /// RocksDb's <c>ERROR_HANDLER_AUTORESUME_COUNT</c>.
    /// </summary>
    ErrorHandlerAutoresumeCount = 180,

    /// <summary>
    /// RocksDb's <c>ERROR_HANDLER_AUTORESUME_RETRY_TOTAL_COUNT</c>.
    /// </summary>
    ErrorHandlerAutoresumeRetryTotalCount = 181,

    /// <summary>
    /// RocksDb's <c>ERROR_HANDLER_AUTORESUME_SUCCESS_COUNT</c>.
    /// </summary>
    ErrorHandlerAutoresumeSuccessCount = 182,

    /// <summary>
    /// Statistics for memtable garbage collection: Raw bytes of data (payload) present on memtable at flush time.
    /// </summary>
    /// <remarks>RocksDb calls this <c>MEMTABLE_PAYLOAD_BYTES_AT_FLUSH</c>.</remarks>
    MemtablePayloadBytesAtFlush = 183,

    /// <summary>
    /// Outdated bytes of data present on memtable at flush time.
    /// </summary>
    /// <remarks>RocksDb calls this <c>MEMTABLE_GARBAGE_BYTES_AT_FLUSH</c>.</remarks>
    MemtableGarbageBytesAtFlush = 184,

    /// <summary>
    /// Bytes read by `VerifyChecksum()` and `VerifyFileChecksums()` APIs.
    /// </summary>
    /// <remarks>RocksDb calls this <c>VERIFY_CHECKSUM_READ_BYTES</c>.</remarks>
    VerifyChecksumReadBytes = 185,

    /// <summary>
    /// Bytes read/written while creating backups
    /// </summary>
    /// <remarks>RocksDb calls this <c>BACKUP_READ_BYTES</c>.</remarks>
    BackupReadBytes = 186,

    /// <summary>
    /// RocksDb's <c>BACKUP_WRITE_BYTES</c>.
    /// </summary>
    BackupWriteBytes = 187,

    /// <summary>
    /// Remote compaction read/write statistics
    /// </summary>
    /// <remarks>RocksDb calls this <c>REMOTE_COMPACT_READ_BYTES</c>.</remarks>
    RemoteCompactReadBytes = 188,

    /// <summary>
    /// RocksDb's <c>REMOTE_COMPACT_WRITE_BYTES</c>.
    /// </summary>
    RemoteCompactWriteBytes = 189,

    /// <summary>
    /// Bytes of output files successfully resumed during compaction
    /// </summary>
    /// <remarks>RocksDb calls this <c>REMOTE_COMPACT_RESUMED_BYTES</c>.</remarks>
    RemoteCompactResumedBytes = 190,

    /// <summary>
    /// Tiered storage related statistics
    /// </summary>
    /// <remarks>RocksDb calls this <c>HOT_FILE_READ_BYTES</c>.</remarks>
    HotFileReadBytes = 191,

    /// <summary>
    /// RocksDb's <c>WARM_FILE_READ_BYTES</c>.
    /// </summary>
    WarmFileReadBytes = 192,

    /// <summary>
    /// RocksDb's <c>COOL_FILE_READ_BYTES</c>.
    /// </summary>
    CoolFileReadBytes = 193,

    /// <summary>
    /// RocksDb's <c>COLD_FILE_READ_BYTES</c>.
    /// </summary>
    ColdFileReadBytes = 194,

    /// <summary>
    /// RocksDb's <c>ICE_FILE_READ_BYTES</c>.
    /// </summary>
    IceFileReadBytes = 195,

    /// <summary>
    /// RocksDb's <c>HOT_FILE_READ_COUNT</c>.
    /// </summary>
    HotFileReadCount = 196,

    /// <summary>
    /// RocksDb's <c>WARM_FILE_READ_COUNT</c>.
    /// </summary>
    WarmFileReadCount = 197,

    /// <summary>
    /// RocksDb's <c>COOL_FILE_READ_COUNT</c>.
    /// </summary>
    CoolFileReadCount = 198,

    /// <summary>
    /// RocksDb's <c>COLD_FILE_READ_COUNT</c>.
    /// </summary>
    ColdFileReadCount = 199,

    /// <summary>
    /// RocksDb's <c>ICE_FILE_READ_COUNT</c>.
    /// </summary>
    IceFileReadCount = 200,

    /// <summary>
    /// Last level and non-last level read statistics
    /// </summary>
    /// <remarks>RocksDb calls this <c>LAST_LEVEL_READ_BYTES</c>.</remarks>
    LastLevelReadBytes = 201,

    /// <summary>
    /// RocksDb's <c>LAST_LEVEL_READ_COUNT</c>.
    /// </summary>
    LastLevelReadCount = 202,

    /// <summary>
    /// RocksDb's <c>NON_LAST_LEVEL_READ_BYTES</c>.
    /// </summary>
    NonLastLevelReadBytes = 203,

    /// <summary>
    /// RocksDb's <c>NON_LAST_LEVEL_READ_COUNT</c>.
    /// </summary>
    NonLastLevelReadCount = 204,

    /// <summary>
    /// Statistics on iterator Seek() (and variants) for each sorted run. I.e. a single user Seek() can result in many sorted run Seek()s. The stats are split between last level and non-last level. Filtered: a filter such as prefix Bloom filter indicate the Seek() would not find anything relevant, so avoided a likely access to data+index blocks.
    /// </summary>
    /// <remarks>RocksDb calls this <c>LAST_LEVEL_SEEK_FILTERED</c>.</remarks>
    LastLevelSeekFiltered = 205,

    /// <summary>
    /// Filter match: a filter such as prefix Bloom filter was queried but did not filter out the seek.
    /// </summary>
    /// <remarks>RocksDb calls this <c>LAST_LEVEL_SEEK_FILTER_MATCH</c>.</remarks>
    LastLevelSeekFilterMatch = 206,

    /// <summary>
    /// At least one data block was accessed for a Seek() (or variant) on a sorted run.
    /// </summary>
    /// <remarks>RocksDb calls this <c>LAST_LEVEL_SEEK_DATA</c>.</remarks>
    LastLevelSeekData = 207,

    /// <summary>
    /// At least one value() was accessed for the seek (suggesting it was useful), and no filter such as prefix Bloom was queried.
    /// </summary>
    /// <remarks>RocksDb calls this <c>LAST_LEVEL_SEEK_DATA_USEFUL_NO_FILTER</c>.</remarks>
    LastLevelSeekDataUsefulNoFilter = 208,

    /// <summary>
    /// At least one value() was accessed for the seek (suggesting it was useful), after querying a filter such as prefix Bloom.
    /// </summary>
    /// <remarks>RocksDb calls this <c>LAST_LEVEL_SEEK_DATA_USEFUL_FILTER_MATCH</c>.</remarks>
    LastLevelSeekDataUsefulFilterMatch = 209,

    /// <summary>
    /// The same set of stats, but for non-last level seeks.
    /// </summary>
    /// <remarks>RocksDb calls this <c>NON_LAST_LEVEL_SEEK_FILTERED</c>.</remarks>
    NonLastLevelSeekFiltered = 210,

    /// <summary>
    /// RocksDb's <c>NON_LAST_LEVEL_SEEK_FILTER_MATCH</c>.
    /// </summary>
    NonLastLevelSeekFilterMatch = 211,

    /// <summary>
    /// RocksDb's <c>NON_LAST_LEVEL_SEEK_DATA</c>.
    /// </summary>
    NonLastLevelSeekData = 212,

    /// <summary>
    /// RocksDb's <c>NON_LAST_LEVEL_SEEK_DATA_USEFUL_NO_FILTER</c>.
    /// </summary>
    NonLastLevelSeekDataUsefulNoFilter = 213,

    /// <summary>
    /// RocksDb's <c>NON_LAST_LEVEL_SEEK_DATA_USEFUL_FILTER_MATCH</c>.
    /// </summary>
    NonLastLevelSeekDataUsefulFilterMatch = 214,

    /// <summary>
    /// Number of block checksum verifications
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CHECKSUM_COMPUTE_COUNT</c>.</remarks>
    BlockChecksumComputeCount = 215,

    /// <summary>
    /// Number of times RocksDB detected a corruption while verifying a block checksum. RocksDB does not remember corruptions that happened during user reads so the same block corruption may be detected multiple times.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_CHECKSUM_MISMATCH_COUNT</c>.</remarks>
    BlockChecksumMismatchCount = 216,

    /// <summary>
    /// RocksDb's <c>MULTIGET_COROUTINE_COUNT</c>.
    /// </summary>
    MultigetCoroutineCount = 217,

    /// <summary>
    /// Time spent in the ReadAsync file system call
    /// </summary>
    /// <remarks>RocksDb calls this <c>READ_ASYNC_MICROS</c>.</remarks>
    ReadAsyncMicros = 218,

    /// <summary>
    /// Number of errors returned to the async read callback
    /// </summary>
    /// <remarks>RocksDb calls this <c>ASYNC_READ_ERROR_COUNT</c>.</remarks>
    AsyncReadErrorCount = 219,

    /// <summary>
    /// Number of lookup into the prefetched tail (see `TABLE_OPEN_PREFETCH_TAIL_READ_BYTES`) that can&apos;t find its data for table open
    /// </summary>
    /// <remarks>RocksDb calls this <c>TABLE_OPEN_PREFETCH_TAIL_MISS</c>.</remarks>
    TableOpenPrefetchTailMiss = 220,

    /// <summary>
    /// Number of lookup into the prefetched tail (see `TABLE_OPEN_PREFETCH_TAIL_READ_BYTES`) that finds its data for table open
    /// </summary>
    /// <remarks>RocksDb calls this <c>TABLE_OPEN_PREFETCH_TAIL_HIT</c>.</remarks>
    TableOpenPrefetchTailHit = 221,

    /// <summary>
    /// Statistics on the filtering by user-defined timestamps # of times timestamps are checked on accessing the table
    /// </summary>
    /// <remarks>RocksDb calls this <c>TIMESTAMP_FILTER_TABLE_CHECKED</c>.</remarks>
    TimestampFilterTableChecked = 222,

    /// <summary>
    /// # of times timestamps can successfully help skip the table access
    /// </summary>
    /// <remarks>RocksDb calls this <c>TIMESTAMP_FILTER_TABLE_FILTERED</c>.</remarks>
    TimestampFilterTableFiltered = 223,

    /// <summary>
    /// Number of times readahead is trimmed during scans when ReadOptions.auto_readahead_size is set.
    /// </summary>
    /// <remarks>RocksDb calls this <c>READAHEAD_TRIMMED</c>.</remarks>
    ReadaheadTrimmed = 224,

    /// <summary>
    /// Number of FIFO compactions that drop files based on different reasons
    /// </summary>
    /// <remarks>RocksDb calls this <c>FIFO_MAX_SIZE_COMPACTIONS</c>.</remarks>
    FifoMaxSizeCompactions = 225,

    /// <summary>
    /// RocksDb's <c>FIFO_TTL_COMPACTIONS</c>.
    /// </summary>
    FifoTtlCompactions = 226,

    /// <summary>
    /// RocksDb's <c>FIFO_CHANGE_TEMPERATURE_COMPACTIONS</c>.
    /// </summary>
    FifoChangeTemperatureCompactions = 227,

    /// <summary>
    /// Number of bytes prefetched during user initiated scan
    /// </summary>
    /// <remarks>RocksDb calls this <c>PREFETCH_BYTES</c>.</remarks>
    PrefetchBytes = 228,

    /// <summary>
    /// Number of prefetched bytes that were actually useful during user initiated scan
    /// </summary>
    /// <remarks>RocksDb calls this <c>PREFETCH_BYTES_USEFUL</c>.</remarks>
    PrefetchBytesUseful = 229,

    /// <summary>
    /// Number of FS reads avoided due to prefetching during user initiated scan
    /// </summary>
    /// <remarks>RocksDb calls this <c>PREFETCH_HITS</c>.</remarks>
    PrefetchHits = 230,

    /// <summary>
    /// Footer corruption detected when opening an SST file for reading
    /// </summary>
    /// <remarks>RocksDb calls this <c>SST_FOOTER_CORRUPTION_COUNT</c>.</remarks>
    SstFooterCorruptionCount = 231,

    /// <summary>
    /// Counters for file read retries with the verify_and_reconstruct_read file system option after detecting a checksum mismatch
    /// </summary>
    /// <remarks>RocksDb calls this <c>FILE_READ_CORRUPTION_RETRY_COUNT</c>.</remarks>
    FileReadCorruptionRetryCount = 232,

    /// <summary>
    /// RocksDb's <c>FILE_READ_CORRUPTION_RETRY_SUCCESS_COUNT</c>.
    /// </summary>
    FileReadCorruptionRetrySuccessCount = 233,

    /// <summary>
    /// Counter for the number of times a WBWI is ingested into the DB. This happens when IngestWriteBatchWithIndex() is used and when large transaction optimization is enabled through TransactionOptions::large_txn_commit_optimize_threshold.
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUMBER_WBWI_INGEST</c>.</remarks>
    NumberWbwiIngest = 234,

    /// <summary>
    /// Failure to load the UDI during SST table open
    /// </summary>
    /// <remarks>RocksDb calls this <c>SST_USER_DEFINED_INDEX_LOAD_FAIL_COUNT</c>.</remarks>
    SstUserDefinedIndexLoadFailCount = 235,

    /// <summary>
    /// MultiScan statistics # of Prepare() calls
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_PREPARE_CALLS</c>.</remarks>
    MultiscanPrepareCalls = 236,

    /// <summary>
    /// # of Prepare() calls that failed
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_PREPARE_ERRORS</c>.</remarks>
    MultiscanPrepareErrors = 237,

    /// <summary>
    /// # of data blocks prefetched from storage during MultiScan
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_BLOCKS_PREFETCHED</c>.</remarks>
    MultiscanBlocksPrefetched = 238,

    /// <summary>
    /// # of blocks found already in cache during MultiScan Prepare
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_BLOCKS_FROM_CACHE</c>.</remarks>
    MultiscanBlocksFromCache = 239,

    /// <summary>
    /// Total bytes prefetched during MultiScan
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_PREFETCH_BYTES</c>.</remarks>
    MultiscanPrefetchBytes = 240,

    /// <summary>
    /// # of prefetched blocks that were never accessed
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_PREFETCH_BLOCKS_WASTED</c>.</remarks>
    MultiscanPrefetchBlocksWasted = 241,

    /// <summary>
    /// # of actual I/O requests issued during MultiScan
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_IO_REQUESTS</c>.</remarks>
    MultiscanIoRequests = 242,

    /// <summary>
    /// # of non-adjacent blocks coalesced into single I/O (within io_coalesce_threshold)
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_IO_COALESCED_NONADJACENT</c>.</remarks>
    MultiscanIoCoalescedNonadjacent = 243,

    /// <summary>
    /// # of seeks that failed validation (out of order, etc.)
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_SEEK_ERRORS</c>.</remarks>
    MultiscanSeekErrors = 244,

    /// <summary>
    /// IODispatcher memory limiting statistics # of bytes granted to prefetch requests
    /// </summary>
    /// <remarks>RocksDb calls this <c>PREFETCH_MEMORY_BYTES_GRANTED</c>.</remarks>
    PrefetchMemoryBytesGranted = 245,

    /// <summary>
    /// # of bytes released from prefetch memory
    /// </summary>
    /// <remarks>RocksDb calls this <c>PREFETCH_MEMORY_BYTES_RELEASED</c>.</remarks>
    PrefetchMemoryBytesReleased = 246,

    /// <summary>
    /// # of prefetch requests that were blocked waiting for memory
    /// </summary>
    /// <remarks>RocksDb calls this <c>PREFETCH_MEMORY_REQUESTS_BLOCKED</c>.</remarks>
    PrefetchMemoryRequestsBlocked = 247,

    /// <summary>
    /// # of range tombstones inserted by read-path conversion from contiguous point tombstones
    /// </summary>
    /// <remarks>RocksDb calls this <c>READ_PATH_RANGE_TOMBSTONES_INSERTED</c>.</remarks>
    ReadPathRangeTombstonesInserted = 248,

    /// <summary>
    /// # of range tombstones not inserted. Reasons include: - iterator&apos;s snapshot predates the memtable - tombstones may be uncommitted (transactions) - memtable already has a covering range tombstone - memtable switched to immutable state
    /// </summary>
    /// <remarks>RocksDb calls this <c>READ_PATH_RANGE_TOMBSTONES_DISCARDED</c>.</remarks>
    ReadPathRangeTombstonesDiscarded = 249,

    /// <summary>
    /// Number of times file open metadata was retrieved from the file system via GetFileOpenMetadata() (when fast_sst_open is enabled)
    /// </summary>
    /// <remarks>RocksDb calls this <c>FILE_OPEN_METADATA_RETRIEVED</c>.</remarks>
    FileOpenMetadataRetrieved = 250,

    /// <summary>
    /// Number of times file open metadata was passed to NewRandomAccessFile() via FileOptions::file_metadata (on DB open / table cache miss)
    /// </summary>
    /// <remarks>RocksDb calls this <c>FILE_OPEN_METADATA_PASSED</c>.</remarks>
    FileOpenMetadataPassed = 251,

    /// <summary>
    /// # of times MANIFEST content validation detected corruption on DB close
    /// </summary>
    /// <remarks>RocksDb calls this <c>MANIFEST_VALIDATION_FAILURE_COUNT</c>.</remarks>
    ManifestValidationFailureCount = 252,

    /// <summary>
    /// Number of flushes triggered because the memtable reached write_buffer_size.
    /// </summary>
    /// <remarks>RocksDb calls this <c>FLUSH_REASON_WRITE_BUFFER_FULL</c>.</remarks>
    FlushReasonWriteBufferFull = 253,

    /// <summary>
    /// Number of flushes triggered by WriteBufferManager memory pressure.
    /// </summary>
    /// <remarks>RocksDb calls this <c>FLUSH_REASON_WRITE_BUFFER_MANAGER</c>.</remarks>
    FlushReasonWriteBufferManager = 254,

    /// <summary>
    /// Number of flushes triggered because the memtable reached memtable_max_range_deletions.
    /// </summary>
    /// <remarks>RocksDb calls this <c>FLUSH_REASON_MEMTABLE_MAX_RANGE_DELETIONS</c>.</remarks>
    FlushReasonMemtableMaxRangeDeletions = 255,

    /// <summary>
    /// Number of atomic flush requests triggered because a memtable reached write_buffer_size.
    /// </summary>
    /// <remarks>RocksDb calls this <c>ATOMIC_FLUSH_REQUEST_REASON_WRITE_BUFFER_FULL</c>.</remarks>
    AtomicFlushRequestReasonWriteBufferFull = 256,

    /// <summary>
    /// Number of atomic flush requests triggered by WriteBufferManager memory pressure.
    /// </summary>
    /// <remarks>RocksDb calls this <c>ATOMIC_FLUSH_REQUEST_REASON_WRITE_BUFFER_MANAGER</c>.</remarks>
    AtomicFlushRequestReasonWriteBufferManager = 257,

    /// <summary>
    /// Number of atomic flush requests triggered because a memtable reached memtable_max_range_deletions.
    /// </summary>
    /// <remarks>RocksDb calls this <c>ATOMIC_FLUSH_REQUEST_REASON_MEMTABLE_MAX_RANGE_DELETIONS</c>.</remarks>
    AtomicFlushRequestReasonMemtableMaxRangeDeletions = 258,

    /// <summary>
    /// Number of atomic flush requests triggered for reasons that do not have a dedicated atomic flush request reason ticker.
    /// </summary>
    /// <remarks>RocksDb calls this <c>ATOMIC_FLUSH_REQUEST_REASON_OTHER</c>.</remarks>
    AtomicFlushRequestReasonOther = 259,

    /// <summary>
    /// Bytes read/written while creating checkpoints
    /// </summary>
    /// <remarks>RocksDb calls this <c>CHECKPOINT_READ_BYTES</c>.</remarks>
    CheckpointReadBytes = 260,

    /// <summary>
    /// RocksDb's <c>CHECKPOINT_WRITE_BYTES</c>.
    /// </summary>
    CheckpointWriteBytes = 261,

    /// <summary>
    /// Number of SubmitReadAsync calls that fell back to a synchronous read
    /// </summary>
    /// <remarks>RocksDb calls this <c>FILE_SUBMIT_ASYNC_READ_FALLBACK</c>.</remarks>
    FileSubmitAsyncReadFallback = 262,
}

/// <summary>
/// A distribution collected by the statistics subsystem.
/// </summary>
/// <remarks>
/// Pass one to <see cref="DbOptions.GetHistogramData(Histogram)"/>.
/// <para>
/// The values are positional in RocksDb's header, so they change between
/// releases when a counter is added or retired. They are generated from the
/// pinned version rather than written out by hand for that reason.
/// </para>
/// </remarks>
public enum Histogram
{
    /// <summary>
    /// RocksDb's <c>DB_GET</c>.
    /// </summary>
    DbGet = 0,

    /// <summary>
    /// RocksDb's <c>DB_WRITE</c>.
    /// </summary>
    DbWrite = 1,

    /// <summary>
    /// RocksDb's <c>COMPACTION_TIME</c>.
    /// </summary>
    CompactionTime = 2,

    /// <summary>
    /// RocksDb's <c>COMPACTION_CPU_TIME</c>.
    /// </summary>
    CompactionCpuTime = 3,

    /// <summary>
    /// RocksDb's <c>SUBCOMPACTION_SETUP_TIME</c>.
    /// </summary>
    SubcompactionSetupTime = 4,

    /// <summary>
    /// RocksDb's <c>TABLE_SYNC_MICROS</c>.
    /// </summary>
    TableSyncMicros = 5,

    /// <summary>
    /// RocksDb's <c>COMPACTION_OUTFILE_SYNC_MICROS</c>.
    /// </summary>
    CompactionOutfileSyncMicros = 6,

    /// <summary>
    /// RocksDb's <c>WAL_FILE_SYNC_MICROS</c>.
    /// </summary>
    WalFileSyncMicros = 7,

    /// <summary>
    /// RocksDb's <c>MANIFEST_FILE_SYNC_MICROS</c>.
    /// </summary>
    ManifestFileSyncMicros = 8,

    /// <summary>
    /// TIME SPENT IN IO DURING TABLE OPEN
    /// </summary>
    /// <remarks>RocksDb calls this <c>TABLE_OPEN_IO_MICROS</c>.</remarks>
    TableOpenIoMicros = 9,

    /// <summary>
    /// RocksDb's <c>DB_MULTIGET</c>.
    /// </summary>
    DbMultiget = 10,

    /// <summary>
    /// RocksDb's <c>READ_BLOCK_COMPACTION_MICROS</c>.
    /// </summary>
    ReadBlockCompactionMicros = 11,

    /// <summary>
    /// RocksDb's <c>READ_BLOCK_GET_MICROS</c>.
    /// </summary>
    ReadBlockGetMicros = 12,

    /// <summary>
    /// RocksDb's <c>WRITE_RAW_BLOCK_MICROS</c>.
    /// </summary>
    WriteRawBlockMicros = 13,

    /// <summary>
    /// RocksDb's <c>NUM_FILES_IN_SINGLE_COMPACTION</c>.
    /// </summary>
    NumFilesInSingleCompaction = 14,

    /// <summary>
    /// RocksDb's <c>DB_SEEK</c>.
    /// </summary>
    DbSeek = 15,

    /// <summary>
    /// RocksDb's <c>WRITE_STALL</c>.
    /// </summary>
    WriteStall = 16,

    /// <summary>
    /// Time spent in reading block-based or plain SST table
    /// </summary>
    /// <remarks>RocksDb calls this <c>SST_READ_MICROS</c>.</remarks>
    SstReadMicros = 17,

    /// <summary>
    /// Time spent in reading SST table (currently only block-based table) or blob file corresponding to `Env::IOActivity`
    /// </summary>
    /// <remarks>RocksDb calls this <c>FILE_READ_FLUSH_MICROS</c>.</remarks>
    FileReadFlushMicros = 18,

    /// <summary>
    /// RocksDb's <c>FILE_READ_COMPACTION_MICROS</c>.
    /// </summary>
    FileReadCompactionMicros = 19,

    /// <summary>
    /// RocksDb's <c>FILE_READ_DB_OPEN_MICROS</c>.
    /// </summary>
    FileReadDbOpenMicros = 20,

    /// <summary>
    /// The following `FILE_READ_*` require stats level greater than `StatsLevel::kExceptDetailedTimers`
    /// </summary>
    /// <remarks>RocksDb calls this <c>FILE_READ_GET_MICROS</c>.</remarks>
    FileReadGetMicros = 21,

    /// <summary>
    /// RocksDb's <c>FILE_READ_MULTIGET_MICROS</c>.
    /// </summary>
    FileReadMultigetMicros = 22,

    /// <summary>
    /// RocksDb's <c>FILE_READ_DB_ITERATOR_MICROS</c>.
    /// </summary>
    FileReadDbIteratorMicros = 23,

    /// <summary>
    /// RocksDb's <c>FILE_READ_VERIFY_DB_CHECKSUM_MICROS</c>.
    /// </summary>
    FileReadVerifyDbChecksumMicros = 24,

    /// <summary>
    /// RocksDb's <c>FILE_READ_VERIFY_FILE_CHECKSUMS_MICROS</c>.
    /// </summary>
    FileReadVerifyFileChecksumsMicros = 25,

    /// <summary>
    /// Time spent in writing SST files
    /// </summary>
    /// <remarks>RocksDb calls this <c>SST_WRITE_MICROS</c>.</remarks>
    SstWriteMicros = 26,

    /// <summary>
    /// Time spent in writing SST table (currently only block-based table) or blob file for flush, compaction or db open
    /// </summary>
    /// <remarks>RocksDb calls this <c>FILE_WRITE_FLUSH_MICROS</c>.</remarks>
    FileWriteFlushMicros = 27,

    /// <summary>
    /// RocksDb's <c>FILE_WRITE_COMPACTION_MICROS</c>.
    /// </summary>
    FileWriteCompactionMicros = 28,

    /// <summary>
    /// RocksDb's <c>FILE_WRITE_DB_OPEN_MICROS</c>.
    /// </summary>
    FileWriteDbOpenMicros = 29,

    /// <summary>
    /// The number of subcompactions actually scheduled during a compaction
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUM_SUBCOMPACTIONS_SCHEDULED</c>.</remarks>
    NumSubcompactionsScheduled = 30,

    /// <summary>
    /// Value size distribution in each operation
    /// </summary>
    /// <remarks>RocksDb calls this <c>BYTES_PER_READ</c>.</remarks>
    BytesPerRead = 31,

    /// <summary>
    /// RocksDb's <c>BYTES_PER_WRITE</c>.
    /// </summary>
    BytesPerWrite = 32,

    /// <summary>
    /// RocksDb's <c>BYTES_PER_MULTIGET</c>.
    /// </summary>
    BytesPerMultiget = 33,

    /// <summary>
    /// RocksDb's <c>COMPRESSION_TIMES_NANOS</c>.
    /// </summary>
    CompressionTimesNanos = 34,

    /// <summary>
    /// RocksDb's <c>DECOMPRESSION_TIMES_NANOS</c>.
    /// </summary>
    DecompressionTimesNanos = 35,

    /// <summary>
    /// Number of merge operands passed to the merge operator in user read requests.
    /// </summary>
    /// <remarks>RocksDb calls this <c>READ_NUM_MERGE_OPERANDS</c>.</remarks>
    ReadNumMergeOperands = 36,

    /// <summary>
    /// BlobDB specific stats Size of keys written to BlobDB. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_KEY_SIZE</c>.</remarks>
    BlobDbKeySize = 37,

    /// <summary>
    /// Size of values written to BlobDB. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_VALUE_SIZE</c>.</remarks>
    BlobDbValueSize = 38,

    /// <summary>
    /// BlobDB Put/PutWithTTL/Write latency. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_WRITE_MICROS</c>.</remarks>
    BlobDbWriteMicros = 39,

    /// <summary>
    /// BlobDB Get latency. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_GET_MICROS</c>.</remarks>
    BlobDbGetMicros = 40,

    /// <summary>
    /// BlobDB MultiGet latency. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_MULTIGET_MICROS</c>.</remarks>
    BlobDbMultigetMicros = 41,

    /// <summary>
    /// BlobDB Seek/SeekToFirst/SeekToLast/SeekForPrev latency. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_SEEK_MICROS</c>.</remarks>
    BlobDbSeekMicros = 42,

    /// <summary>
    /// BlobDB Next latency. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_NEXT_MICROS</c>.</remarks>
    BlobDbNextMicros = 43,

    /// <summary>
    /// BlobDB Prev latency. Only applicable to legacy BlobDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_PREV_MICROS</c>.</remarks>
    BlobDbPrevMicros = 44,

    /// <summary>
    /// Blob file write latency.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BLOB_FILE_WRITE_MICROS</c>.</remarks>
    BlobDbBlobFileWriteMicros = 45,

    /// <summary>
    /// Blob file read latency.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BLOB_FILE_READ_MICROS</c>.</remarks>
    BlobDbBlobFileReadMicros = 46,

    /// <summary>
    /// Blob file sync latency.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_BLOB_FILE_SYNC_MICROS</c>.</remarks>
    BlobDbBlobFileSyncMicros = 47,

    /// <summary>
    /// BlobDB compression time.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_COMPRESSION_MICROS</c>.</remarks>
    BlobDbCompressionMicros = 48,

    /// <summary>
    /// BlobDB decompression time.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOB_DB_DECOMPRESSION_MICROS</c>.</remarks>
    BlobDbDecompressionMicros = 49,

    /// <summary>
    /// Time spent flushing memtable to disk
    /// </summary>
    /// <remarks>RocksDb calls this <c>FLUSH_TIME</c>.</remarks>
    FlushTime = 50,

    /// <summary>
    /// RocksDb's <c>SST_BATCH_SIZE</c>.
    /// </summary>
    SstBatchSize = 51,

    /// <summary>
    /// Number of IOs issued in parallel in a MultiGet batch
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTIGET_IO_BATCH_SIZE</c>.</remarks>
    MultigetIoBatchSize = 52,

    /// <summary>
    /// MultiGet stats logged per level Num of index and filter blocks read from file system per level.
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUM_INDEX_AND_FILTER_BLOCKS_READ_PER_LEVEL</c>.</remarks>
    NumIndexAndFilterBlocksReadPerLevel = 53,

    /// <summary>
    /// Num of sst files read from file system per level.
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUM_SST_READ_PER_LEVEL</c>.</remarks>
    NumSstReadPerLevel = 54,

    /// <summary>
    /// Number of levels requiring IO for MultiGet
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUM_LEVEL_READ_PER_MULTIGET</c>.</remarks>
    NumLevelReadPerMultiget = 55,

    /// <summary>
    /// Error handler statistics
    /// </summary>
    /// <remarks>RocksDb calls this <c>ERROR_HANDLER_AUTORESUME_RETRY_COUNT</c>.</remarks>
    ErrorHandlerAutoresumeRetryCount = 56,

    /// <summary>
    /// Stats related to asynchronous read requests.
    /// </summary>
    /// <remarks>RocksDb calls this <c>ASYNC_READ_BYTES</c>.</remarks>
    AsyncReadBytes = 57,

    /// <summary>
    /// RocksDb's <c>POLL_WAIT_MICROS</c>.
    /// </summary>
    PollWaitMicros = 58,

    /// <summary>
    /// Number of bytes for RocksDB&apos;s prefetching (as opposed to file system&apos;s prefetch) on SST file during compaction read
    /// </summary>
    /// <remarks>RocksDb calls this <c>COMPACTION_PREFETCH_BYTES</c>.</remarks>
    CompactionPrefetchBytes = 59,

    /// <summary>
    /// Number of prefetched bytes discarded by RocksDB.
    /// </summary>
    /// <remarks>RocksDb calls this <c>PREFETCHED_BYTES_DISCARDED</c>.</remarks>
    PrefetchedBytesDiscarded = 60,

    /// <summary>
    /// Wait time for aborting async read in FilePrefetchBuffer destructor
    /// </summary>
    /// <remarks>RocksDb calls this <c>ASYNC_PREFETCH_ABORT_MICROS</c>.</remarks>
    AsyncPrefetchAbortMicros = 61,

    /// <summary>
    /// Number of bytes for RocksDB&apos;s prefetching contents (as opposed to file system&apos;s prefetch) from the end of SST table during block based table open
    /// </summary>
    /// <remarks>RocksDb calls this <c>TABLE_OPEN_PREFETCH_TAIL_READ_BYTES</c>.</remarks>
    TableOpenPrefetchTailReadBytes = 62,

    /// <summary>
    /// Number of operations per transaction.
    /// </summary>
    /// <remarks>RocksDb calls this <c>NUM_OP_PER_TRANSACTION</c>.</remarks>
    NumOpPerTransaction = 63,

    /// <summary>
    /// MultiScan Prefill iterator Prepare cost
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_PREPARE_ITERATORS</c>.</remarks>
    MultiscanPrepareIterators = 64,

    /// <summary>
    /// Total Prepare() latency for MultiScan
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_PREPARE_MICROS</c>.</remarks>
    MultiscanPrepareMicros = 65,

    /// <summary>
    /// Distribution of blocks prefetched per MultiScan Prepare()
    /// </summary>
    /// <remarks>RocksDb calls this <c>MULTISCAN_BLOCKS_PER_PREPARE</c>.</remarks>
    MultiscanBlocksPerPrepare = 66,

    /// <summary>
    /// Time (microseconds) from IODispatcher async read submission until completion callback execution.
    /// </summary>
    /// <remarks>RocksDb calls this <c>IO_DISPATCHER_ASYNC_READ_OBSERVED_COMPLETION_MICROS</c>.</remarks>
    IoDispatcherAsyncReadObservedCompletionMicros = 67,

    /// <summary>
    /// Time (microseconds) IODispatcher spends waiting in FileSystem::Poll().
    /// </summary>
    /// <remarks>RocksDb calls this <c>IO_DISPATCHER_ASYNC_READ_POLL_WAIT_MICROS</c>.</remarks>
    IoDispatcherAsyncReadPollWaitMicros = 68,

    /// <summary>
    /// Time (microseconds) from async read submission until the block consumer starts polling for completion.
    /// </summary>
    /// <remarks>RocksDb calls this <c>IO_DISPATCHER_ASYNC_READ_PREFETCH_LEAD_MICROS</c>.</remarks>
    IoDispatcherAsyncReadPrefetchLeadMicros = 69,

    /// <summary>
    /// Coefficient of variation of key gaps in blocks, scaled by 10000 (e.g., CV of 0.4532 is recorded as 4532). Currently only used by index blocks for uniform key distribution tracking.
    /// </summary>
    /// <remarks>RocksDb calls this <c>BLOCK_KEY_DISTRIBUTION_CV</c>.</remarks>
    BlockKeyDistributionCv = 70,

    /// <summary>
    /// Time (microseconds) in the &quot;prepare&quot; phase of an IngestExternalFile(s) call (validation and reading/linking the files; does not block writes). One sample per successful call; requires stats level &gt; kExceptTimers.
    /// </summary>
    /// <remarks>RocksDb calls this <c>INGEST_EXTERNAL_FILE_PREPARE_TIME</c>.</remarks>
    IngestExternalFilePrepareTime = 71,

    /// <summary>
    /// Time (microseconds) in the &quot;run&quot; phase of an IngestExternalFile(s) call (work under the DB mutex while writes are blocked). One sample per successful call; requires stats level &gt; kExceptTimers.
    /// </summary>
    /// <remarks>RocksDb calls this <c>INGEST_EXTERNAL_FILE_RUN_TIME</c>.</remarks>
    IngestExternalFileRunTime = 72,

    /// <summary>
    /// Time read requests spent waiting for rate limiter refills.
    /// </summary>
    /// <remarks>RocksDb calls this <c>RATE_LIMITER_WAIT_MICROS_READ</c>.</remarks>
    RateLimiterWaitMicrosRead = 73,

    /// <summary>
    /// Time write requests spent waiting for rate limiter refills.
    /// </summary>
    /// <remarks>RocksDb calls this <c>RATE_LIMITER_WAIT_MICROS_WRITE</c>.</remarks>
    RateLimiterWaitMicrosWrite = 74,

    /// <summary>
    /// Distribution of total memtable memory usage at flush start.
    /// </summary>
    /// <remarks>RocksDb calls this <c>FLUSH_MEMTABLE_MEMORY_BYTES</c>.</remarks>
    FlushMemtableMemoryBytes = 75,

    /// <summary>
    /// Distribution of total memtable data size at flush start.
    /// </summary>
    /// <remarks>RocksDb calls this <c>FLUSH_MEMTABLE_TOTAL_DATA_SIZE</c>.</remarks>
    FlushMemtableTotalDataSize = 76,

    /// <summary>
    /// Distribution of total memtable memory usage for write-buffer-full flushes.
    /// </summary>
    /// <remarks>RocksDb calls this <c>FLUSH_WRITE_BUFFER_FULL_MEMTABLE_MEMORY_BYTES</c>.</remarks>
    FlushWriteBufferFullMemtableMemoryBytes = 77,

    /// <summary>
    /// Distribution of total memtable memory usage for WBM-triggered flushes.
    /// </summary>
    /// <remarks>RocksDb calls this <c>FLUSH_WRITE_BUFFER_MANAGER_MEMTABLE_MEMORY_BYTES</c>.</remarks>
    FlushWriteBufferManagerMemtableMemoryBytes = 78,

    /// <summary>
    /// Time spent opening the secondary DB inside DB::OpenAndCompact().
    /// </summary>
    /// <remarks>RocksDb calls this <c>OPEN_AND_COMPACT_DB_OPEN_MICROS</c>.</remarks>
    OpenAndCompactDbOpenMicros = 79,
}
