using System.Security;
using System.Text;

namespace NativeMethodsGenerator;

/// <summary>
/// Generates the public <c>Ticker</c> and <c>Histogram</c> enums from rocksdb's
/// statistics.h.
/// </summary>
/// <remarks>
/// These are not in c.h, which is why they were never generated and why the
/// statistics accessors took bare numbers. Generating them rather than writing
/// them out once matters more here than elsewhere: the values are positional,
/// so rocksdb reordering or retiring a single counter renumbers everything
/// after it, and there are several hundred.
/// </remarks>
public static class StatisticsEnumGenerator
{
    // The sentinels rocksdb puts at the end to size its own arrays. They are
    // not counters and asking for one would be out of range.
    private static readonly string[] Sentinels = ["TICKER_ENUM_MAX", "HISTOGRAM_ENUM_MAX"];

    /// <summary>Generates the file content.</summary>
    public static string Generate(CEnum tickers, CEnum histograms, string version, string url)
    {
        var sb = new StringBuilder();

        sb.AppendLine( "// <auto-generated>");
        sb.AppendLine($"// This file was generated by NativeMethodsGenerator from RocksDb v{version} statistics.h header.");
        sb.AppendLine($"// {url}");
        sb.AppendLine( "// Do not edit manually — re-run the generator to update.");
        sb.AppendLine( "//");
        sb.AppendLine( "// Copyright (c) 2011-present, Facebook, Inc. All rights reserved.");
        sb.AppendLine( "// This source code is licensed under both the GPLv2 (found in the");
        sb.AppendLine( "// COPYING file in the root directory) and Apache 2.0 License");
        sb.AppendLine( "// (found in the LICENSE.Apache file in the root directory).");
        sb.AppendLine( "//");
        sb.AppendLine( "// Those two files live in RocksDb's repository, at");
        sb.AppendLine( "// https://github.com/facebook/rocksdb, not in this one. A copy of the");
        sb.AppendLine( "// Apache 2.0 text ships with this package under licenses/.");
        sb.AppendLine( "//");
        sb.AppendLine( "// Modified from the original: the C++ enum members have been renamed to");
        sb.AppendLine( "// this library's casing and their comments reproduced as XML");
        sb.AppendLine( "// documentation. The numeric values are RocksDb's own. No RocksDb");
        sb.AppendLine( "// implementation code is included or reproduced here.");
        sb.AppendLine( "// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine( "namespace RocksDbNet;");
        sb.AppendLine();

        Emit(
            sb,
            "Ticker",
            tickers,
            "A counter collected by the statistics subsystem.",
            "Pass one to <see cref=\"DbOptions.GetTickerCount(Ticker)\"/>. Every counter is cumulative for the life of the statistics object.");

        sb.AppendLine();

        Emit(
            sb,
            "Histogram",
            histograms,
            "A distribution collected by the statistics subsystem.",
            "Pass one to <see cref=\"DbOptions.GetHistogramData(Histogram)\"/>.");

        return sb.ToString();
    }

    private static void Emit(StringBuilder sb, string name, CEnum source, string summary, string remarks)
    {
        var emitted = new Dictionary<string, string>(StringComparer.Ordinal);

        sb.AppendLine( "/// <summary>");
        sb.AppendLine($"/// {summary}");
        sb.AppendLine( "/// </summary>");
        sb.AppendLine( "/// <remarks>");
        sb.AppendLine($"/// {remarks}");
        sb.AppendLine( "/// <para>");
        sb.AppendLine( "/// The values are positional in RocksDb's header, so they change between");
        sb.AppendLine( "/// releases when a counter is added or retired. They are generated from the");
        sb.AppendLine( "/// pinned version rather than written out by hand for that reason.");
        sb.AppendLine( "/// </para>");
        sb.AppendLine( "/// </remarks>");
        sb.AppendLine($"public enum {name}");
        sb.AppendLine( "{");

        bool first = true;

        foreach (CEnumMember member in source.Members)
        {
            if (Sentinels.Contains(member.Name))
            {
                continue;
            }

            string csharpName = CppEnumParser.ToPascalCase(member.Name);

            if (emitted.TryGetValue(csharpName, out string? clash))
            {
                throw new InvalidOperationException(
                    $"{source.Name} members '{clash}' and '{member.Name}' both become '{csharpName}'. " +
                    "The generator will not emit a name twice; special-case one of them.");
            }

            emitted.Add(csharpName, member.Name);

            if (!first)
            {
                sb.AppendLine();
            }

            first = false;

            // The C comment, when there is one, and the original name either
            // way. The original is what rocksdb's own documentation, its
            // statistics dump and every other binding call it, so it has to
            // stay findable from here.
            sb.AppendLine( "    /// <summary>");

            if (member.Comment is not null)
            {
                sb.AppendLine($"    /// {SecurityElement.Escape(member.Comment)}");
            }
            else
            {
                sb.AppendLine($"    /// RocksDb's <c>{member.Name}</c>.");
            }

            sb.AppendLine( "    /// </summary>");

            if (member.Comment is not null)
            {
                sb.AppendLine($"    /// <remarks>RocksDb calls this <c>{member.Name}</c>.</remarks>");
            }

            sb.AppendLine($"    {csharpName} = {member.Value},");
        }

        sb.AppendLine("}");
    }
}
